In [10]:
import numpy as np
x, y = np.meshgrid(3, 5, indexing='xy', sparse=True)
x

array([[3]])

In [16]:
z = np.array([[0, 1, 2],[3, 4, 5], [6, 7, 8]])
np.max(z[:,0])

6

In [59]:
import numpy as np

# Each row: [x, y, q]
charges = np.array([
    [0.0, 0.0,  1e-6],   # 1 µC at origin
    [1.0, 0.0, -2e-6],   # -2 µC at (1, 0)
    [0.0, 1.0,  3e-6],   # 3 µC at (0, 1)
    [1.0, 1.0, -1e-6],   # -1 µC at (1, 1)
    [0.5, 0.5,  2e-6]    # 2 µC at (0.5, 0.5)
])

range_min =  np.min(charges[:,1]) - (np.mean(charges[:,1]))*0.25
range_max =  np.max(charges[:,1]) + (np.mean(charges[:,1]))*0.25
domain_min = np.min(charges[:,0]) - (np.mean(charges[:,0]))*0.25
domain_max = np.max(charges[:,0]) + (np.mean(charges[:,0]))*0.25 
x, y = np.meshgrid(np.linspace(domain_min, domain_max, num = 10), np.linspace(range_min, range_max, num = 10), indexing='xy')
x

array([[-0.125     ,  0.01388889,  0.15277778,  0.29166667,  0.43055556,
         0.56944444,  0.70833333,  0.84722222,  0.98611111,  1.125     ],
       [-0.125     ,  0.01388889,  0.15277778,  0.29166667,  0.43055556,
         0.56944444,  0.70833333,  0.84722222,  0.98611111,  1.125     ],
       [-0.125     ,  0.01388889,  0.15277778,  0.29166667,  0.43055556,
         0.56944444,  0.70833333,  0.84722222,  0.98611111,  1.125     ],
       [-0.125     ,  0.01388889,  0.15277778,  0.29166667,  0.43055556,
         0.56944444,  0.70833333,  0.84722222,  0.98611111,  1.125     ],
       [-0.125     ,  0.01388889,  0.15277778,  0.29166667,  0.43055556,
         0.56944444,  0.70833333,  0.84722222,  0.98611111,  1.125     ],
       [-0.125     ,  0.01388889,  0.15277778,  0.29166667,  0.43055556,
         0.56944444,  0.70833333,  0.84722222,  0.98611111,  1.125     ],
       [-0.125     ,  0.01388889,  0.15277778,  0.29166667,  0.43055556,
         0.56944444,  0.70833333,  0.84722222

In [65]:
y

array([[-0.125     , -0.125     , -0.125     , -0.125     , -0.125     ,
        -0.125     , -0.125     , -0.125     , -0.125     , -0.125     ],
       [ 0.01388889,  0.01388889,  0.01388889,  0.01388889,  0.01388889,
         0.01388889,  0.01388889,  0.01388889,  0.01388889,  0.01388889],
       [ 0.15277778,  0.15277778,  0.15277778,  0.15277778,  0.15277778,
         0.15277778,  0.15277778,  0.15277778,  0.15277778,  0.15277778],
       [ 0.29166667,  0.29166667,  0.29166667,  0.29166667,  0.29166667,
         0.29166667,  0.29166667,  0.29166667,  0.29166667,  0.29166667],
       [ 0.43055556,  0.43055556,  0.43055556,  0.43055556,  0.43055556,
         0.43055556,  0.43055556,  0.43055556,  0.43055556,  0.43055556],
       [ 0.56944444,  0.56944444,  0.56944444,  0.56944444,  0.56944444,
         0.56944444,  0.56944444,  0.56944444,  0.56944444,  0.56944444],
       [ 0.70833333,  0.70833333,  0.70833333,  0.70833333,  0.70833333,
         0.70833333,  0.70833333,  0.70833333

In [64]:
E_x = np.array([])
E_y = np.array([])

for charge in charges:
    r = x - charge[0]
    E_temp = (charge[2])/(r**2) * np.abs(r)/r #q/r^2*unit(r)
    r = y - charge[1]
    E_temp = (r**2) * (1/charge[2]) * np.abs(r)/r #q/r^2*unit(r)

[0.e+00 0.e+00 1.e-06]
[[-6.40000000e-05  5.18400000e-03  4.28429752e-05  1.17551020e-05
   5.39438085e-06  3.08387864e-06  1.99307958e-06  1.39317388e-06
   1.02836739e-06  7.90123457e-07]
 [-6.40000000e-05  5.18400000e-03  4.28429752e-05  1.17551020e-05
   5.39438085e-06  3.08387864e-06  1.99307958e-06  1.39317388e-06
   1.02836739e-06  7.90123457e-07]
 [-6.40000000e-05  5.18400000e-03  4.28429752e-05  1.17551020e-05
   5.39438085e-06  3.08387864e-06  1.99307958e-06  1.39317388e-06
   1.02836739e-06  7.90123457e-07]
 [-6.40000000e-05  5.18400000e-03  4.28429752e-05  1.17551020e-05
   5.39438085e-06  3.08387864e-06  1.99307958e-06  1.39317388e-06
   1.02836739e-06  7.90123457e-07]
 [-6.40000000e-05  5.18400000e-03  4.28429752e-05  1.17551020e-05
   5.39438085e-06  3.08387864e-06  1.99307958e-06  1.39317388e-06
   1.02836739e-06  7.90123457e-07]
 [-6.40000000e-05  5.18400000e-03  4.28429752e-05  1.17551020e-05
   5.39438085e-06  3.08387864e-06  1.99307958e-06  1.39317388e-06
   1.02836

array([], dtype=float64)

In [56]:
1/r**2

array([[  2.56      ,   2.56      ,   2.56      ,   2.56      ,
          2.56      ,   2.56      ,   2.56      ,   2.56      ,
          2.56      ,   2.56      ],
       [  4.23183673,   4.23183673,   4.23183673,   4.23183673,
          4.23183673,   4.23183673,   4.23183673,   4.23183673,
          4.23183673,   4.23183673],
       [  8.2944    ,   8.2944    ,   8.2944    ,   8.2944    ,
          8.2944    ,   8.2944    ,   8.2944    ,   8.2944    ,
          8.2944    ,   8.2944    ],
       [ 23.04      ,  23.04      ,  23.04      ,  23.04      ,
         23.04      ,  23.04      ,  23.04      ,  23.04      ,
         23.04      ,  23.04      ],
       [207.36      , 207.36      , 207.36      , 207.36      ,
        207.36      , 207.36      , 207.36      , 207.36      ,
        207.36      , 207.36      ],
       [207.36      , 207.36      , 207.36      , 207.36      ,
        207.36      , 207.36      , 207.36      , 207.36      ,
        207.36      , 207.36      ],
       [ 2